### PR TITLE
Fix project used to run pipestem

### PR DESCRIPTION
**Pull request by rmcd-mscb**
This is a test pull request.  I'd been using a separate repo for my testing projects especially for irf_ex.  This is a test pull request.  I reorganized the project/pipestem repo so it could be used with irf_ex, and set my own tests in my intel windows side to use the project/pipestem repo.

### CODE REVIEW

**Comment by rmcd-mscb** [comment]
The modification of the projects/pipestem project is ready to try and run the soil irf_ex which is a coupling of the surface-bmi and this soil-bmi.  It looks like bmiprmssurface_lib would need to be added to the cmakelist files but not sure how that works

**Comment by mdpiper** [comment]
I'd recommend creating a separate repository for coupling examples; this allows the tests for the surface and soil components to be focused on those components alone, reducing the possibility of external side effects.

**Comment by mdpiper** [comment]
I can also help set up a separate repository with cmake, if you'd like.

**Comment by rmcd-mscb** [comment]
Thanks Mark, you've got enough on your plate, but I appreciate the offer very much.  I'll give a try at separate repo for testing the coupling.  I've got good templates for working with cmake and Travis, through your examples of these repos. This was an interesting exercise for me because it helped me wrap my head around Travis, CMake, and even for myself the prms input file, a bit more.

**Pull request closed without merging**
