### PR TITLE
Implement unit tests

### PR DESCRIPTION
**Pull request by mdpiper**
This PR sets up cmake build instructions and unit tests for the PRMS soil component. It also adds CI testing with Travis CI.

### CODE REVIEW

**Comment by mdpiper** [comment]
@rmcd-mscb The getter/setter tests are currently failing, but only because they need to be updated with appropriate variables from the soil component. Would you be willing to tackle this?

**Comment by rmcd-mscb** [comment]
@mdpiper Yes!  I can fill out the getter/setter. Would the appropriate way to do that be to merge this branch then when my local repo is updated checkout a new branch to update the setter getter functions?  Let me know

**Comment by mdpiper** [comment]
@rmcd-mscb Yup! This would work. Alternately, if you'd like to try it, a more "GitHub" way would be to checkout the mdpiper/implement-tests branch locally, make changes on it, then push them. The changes will appear in this PR. I leave it up to you, though; whichever is more convenient.

**Comment by rmcd-mscb** [comment]
@mdpiper A little confused because I thought I had written all these tests.  No matter, because I found some issue and it's always good to review.  Also was able to add a few more tests to the getter functions.  The setter tests are sparse but there are not many vars that have equivalent getters for testing.  Also the set/get are pretty well tested in the irf_ex examples.  Mark if you have suggestions for filling these out, or ideas of setter tests when there are no corresponding getter functions just let me know.  I think the Travis fails are just because I changed the # of i/o vars.  Let me know what you think Mark!  PS only working on the weekend because I like it and it focuses my mind :)

**Comment by mdpiper** [comment]
@rmcd-mscb I'm really sorry, Rich--I see that I did clobber your tests. If this happens again, please let me know because I can quickly rewind history in git to reinstate the version you worked on. Again, I'm really sorry that I made extra work for you.

**Comment by rmcd-mscb** [comment]
@mdpiper No Worries Mark!  They are a little more complete now and I found a few things to tidy-up!

**Comment by mdpiper** [comment]
@rmcd-mscb OK, all tests are passing, and this PR is ready for your review.

**Comment by mdpiper** [comment]
@rmcd-mscb No, no -- you don't have to change the way you work with VS! If you get code working there, I'm happy to tweak it to make it work with cmake. Eventually, I need to set aside time to build netcdf-fortran, etc., on Windows so that you can use the cmake settings in VS.

**Pull request merged**
